import { test } from "node:test";
import assert from "node:assert/strict";
import { findShadowedNoCouponRules } from "./find-shadowed-no-coupon-rules.js";

const rule = (over = {}) => ({
  rule_id: 1,
  coupon_type: "NO_COUPON",
  sort_order: 5,
  stop_rules_processing: false,
  is_active: true,
  website_ids: [1],
  customer_group_ids: [0, 1],
  ...over,
});

test("no conflict with differing priority and no discard", () => {
  const noCoupon = rule({ rule_id: 1, coupon_type: "NO_COUPON", sort_order: 10 });
  const coupon = rule({ rule_id: 2, coupon_type: "SPECIFIC_COUPON", sort_order: 5, stop_rules_processing: false });
  assert.deepEqual(findShadowedNoCouponRules([noCoupon, coupon]), []);
});

test("conflict via equal priority plus discard", () => {
  const noCoupon = rule({ rule_id: 1, coupon_type: "NO_COUPON", sort_order: 5 });
  const coupon = rule({ rule_id: 2, coupon_type: "SPECIFIC_COUPON", sort_order: 5, stop_rules_processing: true });
  const result = findShadowedNoCouponRules([noCoupon, coupon]);
  assert.deepEqual(result, [{
    noCouponRuleId: 1,
    blockingCouponRuleId: 2,
    reason: "equal-or-higher-priority coupon rule discards subsequent rules",
  }]);
});

test("conflict via strictly higher coupon rule priority", () => {
  const noCoupon = rule({ rule_id: 1, coupon_type: "NO_COUPON", sort_order: 10 });
  const coupon = rule({ rule_id: 2, coupon_type: "SPECIFIC_AUTOGENERATED", sort_order: 3, stop_rules_processing: true });
  const result = findShadowedNoCouponRules([noCoupon, coupon]);
  assert.equal(result.length, 1);
  assert.equal(result[0].blockingCouponRuleId, 2);
});

test("no conflict due to disjoint scope", () => {
  const noCoupon = rule({ rule_id: 1, coupon_type: "NO_COUPON", sort_order: 5, website_ids: [1], customer_group_ids: [0] });
  const coupon = rule({ rule_id: 2, coupon_type: "SPECIFIC_COUPON", sort_order: 5, stop_rules_processing: true, website_ids: [2], customer_group_ids: [1] });
  assert.deepEqual(findShadowedNoCouponRules([noCoupon, coupon]), []);
});

test("inactive rules are ignored", () => {
  const noCoupon = rule({ rule_id: 1, coupon_type: "NO_COUPON", sort_order: 5, is_active: false });
  const coupon = rule({ rule_id: 2, coupon_type: "SPECIFIC_COUPON", sort_order: 5, stop_rules_processing: true });
  assert.deepEqual(findShadowedNoCouponRules([noCoupon, coupon]), []);
});

test("no conflict when coupon rule has lower priority even with discard", () => {
  const noCoupon = rule({ rule_id: 1, coupon_type: "NO_COUPON", sort_order: 5 });
  const coupon = rule({ rule_id: 2, coupon_type: "SPECIFIC_COUPON", sort_order: 6, stop_rules_processing: true });
  assert.deepEqual(findShadowedNoCouponRules([noCoupon, coupon]), []);
});

test("multiple no-coupon rules are each checked independently", () => {
  const nc1 = rule({ rule_id: 1, coupon_type: "NO_COUPON", sort_order: 5 });
  const nc2 = rule({ rule_id: 2, coupon_type: "NO_COUPON", sort_order: 20 });
  const c = rule({ rule_id: 3, coupon_type: "SPECIFIC_COUPON", sort_order: 5, stop_rules_processing: true });
  const result = findShadowedNoCouponRules([nc1, nc2, c]);
  const ids = result.map((r) => r.noCouponRuleId).sort();
  assert.deepEqual(ids, [1, 2]);
});
