import { test } from "node:test";
import assert from "node:assert/strict";
import { findDuplicateProductRewrites, isLiveTrafficRow } from "./disabled-rewrite-setting-still-duplicates.js";

const row = (over = {}) => ({
  url_rewrite_id: 1,
  entity_type: "product",
  entity_id: 42,
  request_path: "green-shirt.html",
  target_path: "catalog/product/view/id/42",
  store_id: 1,
  is_autogenerated: 1,
  ...over,
});

test("no pairs when setting enabled", () => {
  const rows = [
    row({ url_rewrite_id: 1, request_path: "green-shirt.html" }),
    row({ url_rewrite_id: 2, request_path: "mens/shirts/green-shirt.html" }),
  ];
  assert.deepEqual(findDuplicateProductRewrites(rows, 42, true), []);
});

test("no pairs when only one row per store", () => {
  const rows = [row({ url_rewrite_id: 1, request_path: "green-shirt.html" })];
  assert.deepEqual(findDuplicateProductRewrites(rows, 42, false), []);
});

test("flags pair when setting disabled and two rows share target", () => {
  const rows = [
    row({ url_rewrite_id: 1, request_path: "green-shirt.html" }),
    row({ url_rewrite_id: 2, request_path: "mens/shirts/green-shirt.html" }),
  ];
  const result = findDuplicateProductRewrites(rows, 42, false);
  assert.deepEqual(result, [{ keep: 1, remove: 2, reason: "duplicate-despite-disabled-setting" }]);
});

test("ignores rows for a different product", () => {
  const rows = [
    row({ url_rewrite_id: 1, entity_id: 42, request_path: "green-shirt.html" }),
    row({ url_rewrite_id: 2, entity_id: 99, request_path: "blue-shirt.html" }),
  ];
  assert.deepEqual(findDuplicateProductRewrites(rows, 42, false), []);
});

test("ignores rows for a different entity type", () => {
  const rows = [
    row({ url_rewrite_id: 1, entity_type: "product", request_path: "green-shirt.html" }),
    row({
      url_rewrite_id: 2,
      entity_type: "category",
      request_path: "mens/shirts.html",
      target_path: "catalog/category/view/id/7",
    }),
  ];
  assert.deepEqual(findDuplicateProductRewrites(rows, 42, false), []);
});

test("same target different store is not paired", () => {
  const rows = [
    row({ url_rewrite_id: 1, request_path: "green-shirt.html", store_id: 1 }),
    row({ url_rewrite_id: 2, request_path: "mens/shirts/green-shirt.html", store_id: 2 }),
  ];
  assert.deepEqual(findDuplicateProductRewrites(rows, 42, false), []);
});

test("different target path is not paired", () => {
  const rows = [
    row({ url_rewrite_id: 1, request_path: "green-shirt.html", target_path: "catalog/product/view/id/42" }),
    row({ url_rewrite_id: 2, request_path: "mens/shirts/red-shirt.html", target_path: "catalog/product/view/id/99" }),
  ];
  assert.deepEqual(findDuplicateProductRewrites(rows, 42, false), []);
});

test("duplicate pairs are returned for each store independently", () => {
  const rows = [
    row({ url_rewrite_id: 1, request_path: "green-shirt.html", store_id: 1 }),
    row({ url_rewrite_id: 2, request_path: "mens/shirts/green-shirt.html", store_id: 1 }),
    row({ url_rewrite_id: 3, request_path: "green-shirt.html", store_id: 2 }),
    row({ url_rewrite_id: 4, request_path: "mens/shirts/green-shirt.html", store_id: 2 }),
  ];
  const result = findDuplicateProductRewrites(rows, 42, false);
  assert.equal(result.length, 2);
  assert.deepEqual(
    result.find((p) => p.keep === 1),
    { keep: 1, remove: 2, reason: "duplicate-despite-disabled-setting" }
  );
  assert.deepEqual(
    result.find((p) => p.keep === 3),
    { keep: 3, remove: 4, reason: "duplicate-despite-disabled-setting" }
  );
});

test("isLiveTrafficRow matches current url_key", () => {
  const r = row({ request_path: "green-shirt.html" });
  assert.equal(isLiveTrafficRow(r, "green-shirt"), true);
});

test("isLiveTrafficRow does not match category path", () => {
  const r = row({ request_path: "mens/shirts/green-shirt.html" });
  assert.equal(isLiveTrafficRow(r, "green-shirt"), false);
});

test("isLiveTrafficRow false when no current url_key", () => {
  const r = row({ request_path: "green-shirt.html" });
  assert.equal(isLiveTrafficRow(r, ""), false);
});
