import { test } from "node:test";
import assert from "node:assert/strict";
import { classifyUrlRewrites } from "./url-rewrite-check.js";

const row = (over = {}) => ({
  url_rewrite_id: 1,
  entity_type: "product",
  entity_id: "10",
  request_path: "green-shirt.html",
  target_path: "catalog/product/view/id/10",
  redirect_type: 0,
  store_id: 1,
  is_autogenerated: 1,
  ...over,
});

test("no duplicates or orphans when all live and unique", () => {
  const live = new Set(["10", "20"]);
  const rows = [row({ url_rewrite_id: 1, entity_id: "10" }), row({ url_rewrite_id: 2, entity_id: "20", request_path: "blue-shirt.html" })];
  const result = classifyUrlRewrites(live, rows);
  assert.deepEqual(result.duplicates, []);
  assert.deepEqual(result.orphans, []);
});

test("same request_path and store is a duplicate group", () => {
  const live = new Set(["10", "11"]);
  const rows = [row({ url_rewrite_id: 1, entity_id: "10" }), row({ url_rewrite_id: 2, entity_id: "11" })];
  const result = classifyUrlRewrites(live, rows);
  assert.deepEqual(result.duplicates, [{ request_path: "green-shirt.html", store_id: 1, ids: [1, 2] }]);
});

test("same path different store is not a duplicate", () => {
  const live = new Set(["10", "11"]);
  const rows = [
    row({ url_rewrite_id: 1, entity_id: "10", store_id: 1 }),
    row({ url_rewrite_id: 2, entity_id: "11", store_id: 2 }),
  ];
  const result = classifyUrlRewrites(live, rows);
  assert.deepEqual(result.duplicates, []);
});

test("missing entity_id is an orphan", () => {
  const live = new Set(["10"]);
  const rows = [row({ url_rewrite_id: 5, entity_id: "999", request_path: "gone.html" })];
  const result = classifyUrlRewrites(live, rows);
  assert.deepEqual(result.orphans, [{ url_rewrite_id: 5, entity_id: "999", request_path: "gone.html" }]);
});

test("live entity is not an orphan", () => {
  const live = new Set(["10"]);
  const rows = [row({ url_rewrite_id: 1, entity_id: "10" })];
  const result = classifyUrlRewrites(live, rows);
  assert.deepEqual(result.orphans, []);
});

test("duplicate ids are sorted ascending", () => {
  const live = new Set(["10", "11"]);
  const rows = [row({ url_rewrite_id: 9, entity_id: "10" }), row({ url_rewrite_id: 3, entity_id: "11" })];
  const result = classifyUrlRewrites(live, rows);
  assert.deepEqual(result.duplicates[0].ids, [3, 9]);
});

test("row can be both orphan and part of a duplicate group", () => {
  const live = new Set(["10"]);
  const rows = [row({ url_rewrite_id: 1, entity_id: "10" }), row({ url_rewrite_id: 2, entity_id: "999" })];
  const result = classifyUrlRewrites(live, rows);
  assert.deepEqual(result.duplicates, [{ request_path: "green-shirt.html", store_id: 1, ids: [1, 2] }]);
  assert.deepEqual(result.orphans, [{ url_rewrite_id: 2, entity_id: "999", request_path: "green-shirt.html" }]);
});

test("no rows produces empty result", () => {
  const result = classifyUrlRewrites(new Set(), []);
  assert.deepEqual(result, { duplicates: [], orphans: [] });
});

test("three way duplicate group", () => {
  const live = new Set(["10", "11", "12"]);
  const rows = [
    row({ url_rewrite_id: 1, entity_id: "10" }),
    row({ url_rewrite_id: 2, entity_id: "11" }),
    row({ url_rewrite_id: 3, entity_id: "12" }),
  ];
  const result = classifyUrlRewrites(live, rows);
  assert.deepEqual(result.duplicates, [{ request_path: "green-shirt.html", store_id: 1, ids: [1, 2, 3] }]);
});
