"""Detect Magento 2 and Adobe Commerce automatic no-coupon cart price rules
that are shadowed by a coupon based cart price rule, safely.

Magento\\SalesRule\\Model\\ResourceModel\\Rule\\Collection::setValidationFilter()
builds one query to fetch cart price rules valid for the current quote,
joining salesrule_coupon and filtering by coupon_type, sort_order (Priority),
and, once a coupon code is entered, by that code matching rule_coupons.code.
That coupon match has historically been applied as a hard AND rather than an
OR against the no-coupon rule type, so a no-coupon rule is excluded from the
candidate set entirely the instant a coupon rule exists and a code is
entered, not merely failing its conditions. Even when both rules are
fetched, a coupon rule with an equal or higher priority and
stop_rules_processing true stops the no-coupon rule from contributing a
discount.

This reports every shadowed pair by default. It never writes a rule change.
The only gated output, behind DRY_RUN=false and a human confirmation,
prints (does not execute) the PUT /rest/V1/salesRules/{rule_id} payload that
would fix the pair, for manual review. Run on a schedule. Safe to run again
and again.

Guide: https://www.allanninal.dev/magento/no-coupon-rule-disabled-by-coupon-rule/
"""
import os
import logging
import requests

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("find_shadowed_no_coupon_rules")

MAGENTO_URL = os.environ["MAGENTO_URL"].rstrip("/")
TOKEN = os.environ["MAGENTO_ADMIN_TOKEN"]
DRY_RUN = os.environ.get("DRY_RUN", "true").lower() == "true"


def magento_get(path, params=None):
    r = requests.get(
        f"{MAGENTO_URL}/rest/V1{path}",
        params=params or {},
        headers={"Authorization": f"Bearer {TOKEN}"},
        timeout=30,
    )
    r.raise_for_status()
    return r.json()


def active_cart_price_rules(page_size=100):
    params = {
        "searchCriteria[filterGroups][0][filters][0][field]": "is_active",
        "searchCriteria[filterGroups][0][filters][0][value]": 1,
        "searchCriteria[filterGroups][0][filters][0][conditionType]": "eq",
        "searchCriteria[pageSize]": page_size,
    }
    return magento_get("/salesRules", params)["items"]


def rule_id_for_coupon_code(code):
    params = {
        "searchCriteria[filterGroups][0][filters][0][field]": "code",
        "searchCriteria[filterGroups][0][filters][0][value]": code,
        "searchCriteria[filterGroups][0][filters][0][conditionType]": "eq",
    }
    items = magento_get("/coupons/search", params)["items"]
    return items[0]["rule_id"] if items else None


def find_shadowed_no_coupon_rules(rules):
    """Pure function. Input is a list of plain dict rules shaped like:
    { rule_id, coupon_type ('NO_COUPON'|'SPECIFIC_COUPON'|'SPECIFIC_AUTOGENERATED'),
      sort_order, stop_rules_processing, is_active, website_ids, customer_group_ids }.
    Returns a list of { noCouponRuleId, blockingCouponRuleId, reason }.
    """
    no_coupon = [r for r in rules if r.get("is_active") and r.get("coupon_type") == "NO_COUPON"]
    coupon = [r for r in rules if r.get("is_active") and r.get("coupon_type") != "NO_COUPON"]

    conflicts = []
    for nc in no_coupon:
        for c in coupon:
            shares_website = bool(set(nc.get("website_ids") or []) & set(c.get("website_ids") or []))
            shares_group = bool(set(nc.get("customer_group_ids") or []) & set(c.get("customer_group_ids") or []))
            if not (shares_website and shares_group):
                continue
            if c.get("sort_order", 0) <= nc.get("sort_order", 0) and c.get("stop_rules_processing") is True:
                conflicts.append({
                    "noCouponRuleId": nc["rule_id"],
                    "blockingCouponRuleId": c["rule_id"],
                    "reason": "equal-or-higher-priority coupon rule discards subsequent rules",
                })
    return conflicts


def to_plain_rule(raw):
    return {
        "rule_id": raw["rule_id"],
        "coupon_type": raw.get("coupon_type", "NO_COUPON"),
        "sort_order": raw.get("sort_order", 0),
        "stop_rules_processing": bool(raw.get("stop_rules_processing")),
        "is_active": bool(raw.get("is_active")),
        "website_ids": raw.get("website_ids") or [],
        "customer_group_ids": raw.get("customer_group_ids") or [],
    }


def print_proposed_fix(conflict, rules_by_id):
    coupon_rule = rules_by_id[conflict["blockingCouponRuleId"]]
    no_coupon_rule = rules_by_id[conflict["noCouponRuleId"]]
    lowered_sort_order = no_coupon_rule["sort_order"] - 1
    log.warning(
        "Proposed fix for rule %s shadowing rule %s (not executed, review manually):\n"
        "  PUT /rest/V1/salesRules/%s\n"
        "  { \"rule\": { \"rule_id\": %s, \"sort_order\": %s } }  // was %s\n"
        "  or\n"
        "  { \"rule\": { \"rule_id\": %s, \"stop_rules_processing\": false } }  // was true",
        conflict["blockingCouponRuleId"], conflict["noCouponRuleId"],
        conflict["blockingCouponRuleId"], conflict["blockingCouponRuleId"],
        lowered_sort_order, coupon_rule["sort_order"],
        conflict["blockingCouponRuleId"],
    )


def run():
    raw_rules = active_cart_price_rules()
    rules = [to_plain_rule(r) for r in raw_rules]
    rules_by_id = {r["rule_id"]: r for r in rules}

    conflicts = find_shadowed_no_coupon_rules(rules)
    for conflict in conflicts:
        nc = rules_by_id[conflict["noCouponRuleId"]]
        c = rules_by_id[conflict["blockingCouponRuleId"]]
        log.warning(
            "No-coupon rule %s is shadowed by coupon rule %s: %s "
            "(no_coupon sort_order=%s, coupon sort_order=%s, coupon stop_rules_processing=%s)",
            conflict["noCouponRuleId"], conflict["blockingCouponRuleId"], conflict["reason"],
            nc["sort_order"], c["sort_order"], c["stop_rules_processing"],
        )
        if not DRY_RUN:
            print_proposed_fix(conflict, rules_by_id)

    log.info("Done. %d shadowed no-coupon rule(s) found.", len(conflicts))


if __name__ == "__main__":
    run()
