from find_shadowed_no_coupon_rules import find_shadowed_no_coupon_rules


def rule(**over):
    base = {
        "rule_id": 1,
        "coupon_type": "NO_COUPON",
        "sort_order": 5,
        "stop_rules_processing": False,
        "is_active": True,
        "website_ids": [1],
        "customer_group_ids": [0, 1],
    }
    base.update(over)
    return base


def test_no_conflict_with_differing_priority_and_no_discard():
    no_coupon = rule(rule_id=1, coupon_type="NO_COUPON", sort_order=10)
    coupon = rule(rule_id=2, coupon_type="SPECIFIC_COUPON", sort_order=5, stop_rules_processing=False)
    assert find_shadowed_no_coupon_rules([no_coupon, coupon]) == []


def test_conflict_via_equal_priority_plus_discard():
    no_coupon = rule(rule_id=1, coupon_type="NO_COUPON", sort_order=5)
    coupon = rule(rule_id=2, coupon_type="SPECIFIC_COUPON", sort_order=5, stop_rules_processing=True)
    result = find_shadowed_no_coupon_rules([no_coupon, coupon])
    assert result == [{
        "noCouponRuleId": 1,
        "blockingCouponRuleId": 2,
        "reason": "equal-or-higher-priority coupon rule discards subsequent rules",
    }]


def test_conflict_via_strictly_higher_coupon_rule_priority():
    no_coupon = rule(rule_id=1, coupon_type="NO_COUPON", sort_order=10)
    coupon = rule(rule_id=2, coupon_type="SPECIFIC_AUTOGENERATED", sort_order=3, stop_rules_processing=True)
    result = find_shadowed_no_coupon_rules([no_coupon, coupon])
    assert len(result) == 1
    assert result[0]["blockingCouponRuleId"] == 2


def test_no_conflict_due_to_disjoint_scope():
    no_coupon = rule(rule_id=1, coupon_type="NO_COUPON", sort_order=5, website_ids=[1], customer_group_ids=[0])
    coupon = rule(rule_id=2, coupon_type="SPECIFIC_COUPON", sort_order=5, stop_rules_processing=True,
                  website_ids=[2], customer_group_ids=[1])
    assert find_shadowed_no_coupon_rules([no_coupon, coupon]) == []


def test_inactive_rules_are_ignored():
    no_coupon = rule(rule_id=1, coupon_type="NO_COUPON", sort_order=5, is_active=False)
    coupon = rule(rule_id=2, coupon_type="SPECIFIC_COUPON", sort_order=5, stop_rules_processing=True)
    assert find_shadowed_no_coupon_rules([no_coupon, coupon]) == []


def test_no_conflict_when_coupon_rule_lower_priority_even_with_discard():
    no_coupon = rule(rule_id=1, coupon_type="NO_COUPON", sort_order=5)
    coupon = rule(rule_id=2, coupon_type="SPECIFIC_COUPON", sort_order=6, stop_rules_processing=True)
    assert find_shadowed_no_coupon_rules([no_coupon, coupon]) == []


def test_multiple_no_coupon_rules_each_checked_independently():
    nc1 = rule(rule_id=1, coupon_type="NO_COUPON", sort_order=5)
    nc2 = rule(rule_id=2, coupon_type="NO_COUPON", sort_order=20)
    c = rule(rule_id=3, coupon_type="SPECIFIC_COUPON", sort_order=5, stop_rules_processing=True)
    result = find_shadowed_no_coupon_rules([nc1, nc2, c])
    ids = sorted(r["noCouponRuleId"] for r in result)
    assert ids == [1, 2]
