import { test } from "node:test";
import assert from "node:assert/strict";
import { resolveUrlKeyCollisions } from "./duplicate-url-key.js";

const product = (over = {}) => ({ sku: "SKU-1", entityId: 1, urlKey: "blue-widget", updatedAt: "2026-01-01T00:00:00Z", ...over });
const row = (over = {}) => ({ entityId: 1, requestPath: "blue-widget.html", storeId: 1, isAutogenerated: true, ...over });

test("no decisions when request_path is unique", () => {
  const products = [product({ sku: "SKU-1", entityId: 1 })];
  const index = new Map([["blue-widget.html", [row({ entityId: 1 })]]]);
  assert.deepEqual(resolveUrlKeyCollisions(products, index), []);
});

test("lowest entityId is kept when both autogenerated", () => {
  const products = [product({ sku: "SKU-1", entityId: 1 }), product({ sku: "SKU-2", entityId: 2, urlKey: "blue-widget" })];
  const index = new Map([["blue-widget.html", [row({ entityId: 1 }), row({ entityId: 2 })]]]);
  const decisions = resolveUrlKeyCollisions(products, index);
  const kept = decisions.find((d) => d.action === "keep");
  const renamed = decisions.find((d) => d.action === "rename");
  assert.equal(kept.sku, "SKU-1");
  assert.equal(renamed.sku, "SKU-2");
  assert.equal(renamed.newUrlKey, "sku-2-blue-widget");
});

test("manual redirect is kept over autogenerated", () => {
  const products = [product({ sku: "SKU-1", entityId: 1 }), product({ sku: "SKU-2", entityId: 2, urlKey: "blue-widget" })];
  const index = new Map([["blue-widget.html", [row({ entityId: 1, isAutogenerated: true }), row({ entityId: 2, isAutogenerated: false })]]]);
  const decisions = resolveUrlKeyCollisions(products, index);
  const kept = decisions.find((d) => d.action === "keep");
  assert.equal(kept.sku, "SKU-2");
});

test("new url_key is slugified", () => {
  const products = [product({ sku: "SKU-1", entityId: 1 }), product({ sku: "SKU 2!", entityId: 2, urlKey: "Blue Widget" })];
  const index = new Map([["blue-widget.html", [row({ entityId: 1 }), row({ entityId: 2 })]]]);
  const decisions = resolveUrlKeyCollisions(products, index);
  const renamed = decisions.find((d) => d.action === "rename");
  assert.equal(renamed.newUrlKey, "sku-2-blue-widget");
});

test("three way collision keeps only one", () => {
  const products = [product({ sku: "A", entityId: 3 }), product({ sku: "B", entityId: 1 }), product({ sku: "C", entityId: 2 })];
  const index = new Map([["blue-widget.html", [row({ entityId: 3 }), row({ entityId: 1 }), row({ entityId: 2 })]]]);
  const decisions = resolveUrlKeyCollisions(products, index);
  const kept = decisions.filter((d) => d.action === "keep");
  const renamed = decisions.filter((d) => d.action === "rename");
  assert.equal(kept.length, 1);
  assert.equal(kept[0].sku, "B");
  assert.equal(renamed.length, 2);
});

test("missing product for a row is skipped", () => {
  const products = [product({ sku: "SKU-1", entityId: 1 })];
  const index = new Map([["blue-widget.html", [row({ entityId: 1 }), row({ entityId: 99 })]]]);
  const decisions = resolveUrlKeyCollisions(products, index);
  assert.equal(decisions.length, 1);
});

test("different store ids do not collide when grouped separately", () => {
  const products = [product({ sku: "SKU-1", entityId: 1 }), product({ sku: "SKU-2", entityId: 2, urlKey: "blue-widget" })];
  const index = new Map([
    ["blue-widget.html-store1", [row({ entityId: 1, storeId: 1 })]],
    ["blue-widget.html-store2", [row({ entityId: 2, storeId: 2 })]],
  ]);
  const decisions = resolveUrlKeyCollisions(products, index);
  assert.deepEqual(decisions, []);
});
