/**
 * Detect duplicate Magento url_key collisions that block a product resave,
 * and repair the fixable ones, safely.
 *
 * Magento 1 and many external carts or PIMs never enforced url_key
 * uniqueness, so a migrated catalog can carry two or more products whose
 * url_key collides once the store's URL suffix and category path are
 * applied. Magento 2 enforces a unique constraint on
 * url_rewrite(request_path, store_id), so resaving one of the colliding
 * products throws AlreadyExistsException.
 *
 * This script fetches every product over REST, groups them by their
 * expected request_path, keeps the row Magento already treats as
 * authoritative, and proposes a new url_key for every other colliding
 * product. It only calls the repair PUT when DRY_RUN=false.
 *
 * Guide: https://www.allanninal.dev/magento/duplicate-url-key-blocks-resave/
 */
import { pathToFileURL } from "node:url";

const MAGENTO_URL = (process.env.MAGENTO_URL || "https://example.test").replace(/\/+$/, "");
const TOKEN = process.env.MAGENTO_ADMIN_TOKEN || "dummy-token";
const HEADERS = { Authorization: `Bearer ${TOKEN}`, "Content-Type": "application/json" };
const URL_SUFFIX = process.env.URL_SUFFIX || ".html";
const DRY_RUN = (process.env.DRY_RUN || "true").toLowerCase() === "true";

function slugify(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").replace(/-+/g, "-");
}

function pickKeeper(rows) {
  const manual = rows.filter((r) => !r.isAutogenerated);
  const pool = manual.length ? manual : rows;
  return pool.reduce((a, b) => (b.entityId < a.entityId ? b : a));
}

/**
 * Pure decision function. Groups url_rewrite rows by (request_path,
 * store_id) via requestPathIndex, and for any group spanning more than one
 * entityId, picks a keeper (manual redirect over autogenerated, else lowest
 * entityId), and derives a deterministic new url_key of sku-originalUrlKey
 * (lowercased, slugified) for every other product in the group. No HTTP or
 * DB calls; fully unit-testable with fixtures.
 */
export function resolveUrlKeyCollisions(products, requestPathIndex) {
  const decisions = [];
  for (const [requestPath, rows] of requestPathIndex) {
    const entityIds = new Set(rows.map((r) => r.entityId));
    if (entityIds.size <= 1) continue;
    const keeperRow = pickKeeper(rows);
    for (const row of rows) {
      const product = products.find((p) => p.entityId === row.entityId);
      if (!product) continue;
      if (row.entityId === keeperRow.entityId) {
        decisions.push({ sku: product.sku, oldUrlKey: product.urlKey, newUrlKey: product.urlKey, requestPath, action: "keep" });
      } else {
        const newKey = slugify(`${product.sku}-${product.urlKey}`);
        decisions.push({ sku: product.sku, oldUrlKey: product.urlKey, newUrlKey: newKey, requestPath, action: "rename" });
      }
    }
  }
  return decisions;
}

function customAttr(attrs, code, fallback = null) {
  for (const a of attrs || []) {
    if (a.attribute_code === code) return a.value;
  }
  return fallback;
}

async function apiGet(path, params = {}) {
  const url = new URL(`${MAGENTO_URL}/rest/V1${path}`);
  for (const [k, v] of Object.entries(params)) url.searchParams.set(k, v);
  const res = await fetch(url, { headers: HEADERS });
  if (!res.ok) throw new Error(`Magento ${res.status}`);
  return res.json();
}

async function apiPut(path, payload) {
  const res = await fetch(`${MAGENTO_URL}/rest/V1${path}`, {
    method: "PUT",
    headers: HEADERS,
    body: JSON.stringify(payload),
  });
  if (!res.ok) throw new Error(`Magento ${res.status}`);
  return res.json();
}

async function fetchProducts() {
  const products = [];
  let page = 1;
  while (true) {
    const params = { "searchCriteria[pageSize]": 100, "searchCriteria[currentPage]": page };
    const result = await apiGet("/products", params);
    const items = result.items || [];
    for (const item of items) {
      products.push({
        sku: item.sku,
        entityId: item.id,
        urlKey: customAttr(item.custom_attributes, "url_key", item.sku),
        updatedAt: item.updated_at || "",
      });
    }
    if (items.length < 100) return products;
    page++;
  }
}

function buildRequestPathIndex(products, urlSuffix) {
  const index = new Map();
  for (const p of products) {
    const requestPath = `${p.urlKey}${urlSuffix}`;
    if (!index.has(requestPath)) index.set(requestPath, []);
    index.get(requestPath).push({ entityId: p.entityId, requestPath, storeId: 1, isAutogenerated: true });
  }
  return index;
}

async function renameUrlKey(sku, newUrlKey) {
  const payload = {
    product: { sku, custom_attributes: [{ attribute_code: "url_key", value: newUrlKey }] },
  };
  return apiPut(`/products/${sku}`, payload);
}

export async function run() {
  const products = await fetchProducts();
  const requestPathIndex = buildRequestPathIndex(products, URL_SUFFIX);
  const decisions = resolveUrlKeyCollisions(products, requestPathIndex);

  let renamed = 0;
  for (const decision of decisions) {
    if (decision.action !== "rename") continue;
    console.warn(`Collision on ${decision.requestPath}: sku=${decision.sku} ${decision.oldUrlKey} -> ${decision.newUrlKey}`);
    if (!DRY_RUN) await renameUrlKey(decision.sku, decision.newUrlKey);
    renamed++;
  }

  console.log(`Done. ${renamed} colliding product(s) ${DRY_RUN ? "to rename" : "renamed"}.`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  run().catch((err) => { console.error(err); process.exit(1); });
}
