from url_rewrite_check import classify_url_rewrites


def row(**over):
    base = {
        "url_rewrite_id": 1,
        "entity_type": "product",
        "entity_id": "10",
        "request_path": "green-shirt.html",
        "target_path": "catalog/product/view/id/10",
        "redirect_type": 0,
        "store_id": 1,
        "is_autogenerated": 1,
    }
    base.update(over)
    return base


def test_no_duplicates_or_orphans_when_all_live_and_unique():
    live = {"10", "20"}
    rows = [row(url_rewrite_id=1, entity_id="10"), row(url_rewrite_id=2, entity_id="20", request_path="blue-shirt.html")]
    result = classify_url_rewrites(live, rows)
    assert result["duplicates"] == []
    assert result["orphans"] == []


def test_same_request_path_and_store_is_a_duplicate_group():
    live = {"10", "11"}
    rows = [
        row(url_rewrite_id=1, entity_id="10"),
        row(url_rewrite_id=2, entity_id="11"),
    ]
    result = classify_url_rewrites(live, rows)
    assert result["duplicates"] == [
        {"request_path": "green-shirt.html", "store_id": 1, "ids": [1, 2]}
    ]


def test_same_path_different_store_is_not_a_duplicate():
    live = {"10", "11"}
    rows = [
        row(url_rewrite_id=1, entity_id="10", store_id=1),
        row(url_rewrite_id=2, entity_id="11", store_id=2),
    ]
    result = classify_url_rewrites(live, rows)
    assert result["duplicates"] == []


def test_missing_entity_id_is_an_orphan():
    live = {"10"}
    rows = [row(url_rewrite_id=5, entity_id="999", request_path="gone.html")]
    result = classify_url_rewrites(live, rows)
    assert result["orphans"] == [
        {"url_rewrite_id": 5, "entity_id": "999", "request_path": "gone.html"}
    ]


def test_live_entity_is_not_an_orphan():
    live = {"10"}
    rows = [row(url_rewrite_id=1, entity_id="10")]
    result = classify_url_rewrites(live, rows)
    assert result["orphans"] == []


def test_duplicate_ids_are_sorted_ascending():
    live = {"10", "11"}
    rows = [
        row(url_rewrite_id=9, entity_id="10"),
        row(url_rewrite_id=3, entity_id="11"),
    ]
    result = classify_url_rewrites(live, rows)
    assert result["duplicates"][0]["ids"] == [3, 9]


def test_row_can_be_both_orphan_and_part_of_a_duplicate_group():
    live = {"10"}
    rows = [
        row(url_rewrite_id=1, entity_id="10"),
        row(url_rewrite_id=2, entity_id="999"),
    ]
    result = classify_url_rewrites(live, rows)
    assert result["duplicates"] == [
        {"request_path": "green-shirt.html", "store_id": 1, "ids": [1, 2]}
    ]
    assert result["orphans"] == [
        {"url_rewrite_id": 2, "entity_id": "999", "request_path": "green-shirt.html"}
    ]


def test_no_rows_produces_empty_result():
    result = classify_url_rewrites(set(), [])
    assert result == {"duplicates": [], "orphans": []}


def test_three_way_duplicate_group():
    live = {"10", "11", "12"}
    rows = [
        row(url_rewrite_id=1, entity_id="10"),
        row(url_rewrite_id=2, entity_id="11"),
        row(url_rewrite_id=3, entity_id="12"),
    ]
    result = classify_url_rewrites(live, rows)
    assert result["duplicates"] == [
        {"request_path": "green-shirt.html", "store_id": 1, "ids": [1, 2, 3]}
    ]
