"""Detect duplicate and orphaned Magento url_rewrite rows and repair the
fixable ones, safely.

url_rewrite has no public REST endpoint, so this script never writes to it
directly. It fetches the live product and category ids over REST, reads a
read-only export of url_rewrite (CSV or direct DB read), classifies rows into
duplicates (same request_path and store_id) and orphans (entity_id not in the
live set), and repairs a fixable row by PUTting the owning product or
category with its own unchanged url_key, which makes Magento regenerate and
supersede its own rewrite row. True orphans with no live entity_id at all are
only reported, since removing them needs CLI or direct database access plus a
reindex. Report only by default.

Guide: https://www.allanninal.dev/magento/duplicate-url-rewrite-rows-404/
"""
import os
import csv
import logging
import requests

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("url_rewrite_check")

MAGENTO_URL = os.environ["MAGENTO_URL"].rstrip("/")
TOKEN = os.environ["MAGENTO_ADMIN_TOKEN"]
HEADERS = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}
DRY_RUN = os.environ.get("DRY_RUN", "true").lower() == "true"
REWRITE_EXPORT_CSV = os.environ.get("URL_REWRITE_EXPORT_CSV", "url_rewrite_export.csv")


def api_get(path, params=None):
    r = requests.get(f"{MAGENTO_URL}/rest/V1{path}", headers=HEADERS, params=params or {}, timeout=30)
    r.raise_for_status()
    return r.json()


def api_put(path, payload):
    r = requests.put(f"{MAGENTO_URL}/rest/V1{path}", headers=HEADERS, json=payload, timeout=30)
    r.raise_for_status()
    return r.json()


def custom_attr(attrs, code, default=None):
    for a in attrs or []:
        if a.get("attribute_code") == code:
            return a.get("value")
    return default


def fetch_live_product_ids_and_keys():
    ids, keys, page = set(), {}, 1
    while True:
        params = {
            "searchCriteria[filterGroups][0][filters][0][field]": "status",
            "searchCriteria[filterGroups][0][filters][0][value]": 1,
            "searchCriteria[filterGroups][0][filters][0][conditionType]": "eq",
            "searchCriteria[pageSize]": 100,
            "searchCriteria[currentPage]": page,
        }
        result = api_get("/products", params)
        items = result.get("items", [])
        for item in items:
            entity_id = str(item["id"])
            ids.add(entity_id)
            keys[entity_id] = {
                "sku": item["sku"],
                "url_key": custom_attr(item.get("custom_attributes"), "url_key"),
            }
        if len(items) < 100:
            return ids, keys
        page += 1


def fetch_live_category_ids():
    result = api_get("/categories/list", {"searchCriteria[pageSize]": 500})
    return {str(item["id"]) for item in result.get("items", [])}


def read_url_rewrite_export(path):
    """Read a read-only export of the url_rewrite table (CSV columns:
    url_rewrite_id, entity_type, entity_id, request_path, target_path,
    redirect_type, store_id, is_autogenerated). Produced by an Admin grid
    export or a read-only DB query, never written back to directly."""
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            rows.append({
                "url_rewrite_id": int(row["url_rewrite_id"]),
                "entity_type": row["entity_type"],
                "entity_id": row["entity_id"],
                "request_path": row["request_path"],
                "target_path": row.get("target_path", ""),
                "redirect_type": int(row.get("redirect_type", 0) or 0),
                "store_id": int(row["store_id"]),
                "is_autogenerated": int(row.get("is_autogenerated", 0) or 0),
            })
    return rows


def classify_url_rewrites(live_entity_ids, rewrite_rows):
    """Pure decision logic. Groups rewrite_rows by (request_path, store_id) to
    find groups with length > 1 (duplicates, keeping the newest
    url_rewrite_id as canonical), and separately filters rows whose
    entity_id is absent from live_entity_ids (orphans). No network or DB
    calls, fully unit-testable with fixture arrays."""
    groups = {}
    for row in rewrite_rows:
        key = (row["request_path"], row["store_id"])
        groups.setdefault(key, []).append(row)

    duplicates = []
    for (request_path, store_id), rows in groups.items():
        if len(rows) > 1:
            duplicates.append({
                "request_path": request_path,
                "store_id": store_id,
                "ids": sorted(r["url_rewrite_id"] for r in rows),
            })

    orphans = [
        {
            "url_rewrite_id": row["url_rewrite_id"],
            "entity_id": row["entity_id"],
            "request_path": row["request_path"],
        }
        for row in rewrite_rows
        if str(row["entity_id"]) not in live_entity_ids
    ]

    return {"duplicates": duplicates, "orphans": orphans}


def repair_product_url_key(sku, url_key):
    payload = {"product": {"sku": sku, "custom_attributes": [
        {"attribute_code": "url_key", "value": url_key}
    ]}}
    return api_put(f"/products/{sku}", payload)


def run():
    live_product_ids, product_keys = fetch_live_product_ids_and_keys()
    live_category_ids = fetch_live_category_ids()
    live_entity_ids = live_product_ids | live_category_ids

    rewrite_rows = read_url_rewrite_export(REWRITE_EXPORT_CSV)
    result = classify_url_rewrites(live_entity_ids, rewrite_rows)

    for dup in result["duplicates"]:
        log.warning(
            "Duplicate request_path=%s store_id=%s ids=%s",
            dup["request_path"], dup["store_id"], dup["ids"],
        )
        newest_id = dup["ids"][-1]
        newest_row = next(r for r in rewrite_rows if r["url_rewrite_id"] == newest_id)
        entity_id = newest_row["entity_id"]
        info = product_keys.get(entity_id)
        if not info or not info.get("url_key"):
            log.info("Duplicate entity_id=%s is not a live product, skipping repair", entity_id)
            continue
        payload_preview = {"product": {"sku": info["sku"], "custom_attributes": [
            {"attribute_code": "url_key", "value": info["url_key"]}
        ]}}
        log.info("%s sku=%s payload=%s", "Would PUT" if DRY_RUN else "PUTting", info["sku"], payload_preview)
        if not DRY_RUN:
            repair_product_url_key(info["sku"], info["url_key"])

    for orphan in result["orphans"]:
        log.warning(
            "Orphan url_rewrite_id=%s entity_id=%s request_path=%s: no live entity, flagged for CLI cleanup",
            orphan["url_rewrite_id"], orphan["entity_id"], orphan["request_path"],
        )

    log.info(
        "Done. %d duplicate group(s), %d orphan row(s) found.",
        len(result["duplicates"]), len(result["orphans"]),
    )


if __name__ == "__main__":
    run()
