"""Detect Magento products that still get a category/product url_rewrite
duplicate even though catalog/seo/generate_category_product_rewrites is off.

This is a confirmed core bug (magento/magento2 issues 38317 and 39070), not a
misconfiguration: ProductProcessUrlRewriteSavingObserver writes a plain
product rewrite on every product save regardless of the setting, while
CategoryProcessUrlRewriteSavingObserver and CanonicalUrlRewriteGenerator can
still write a category-prefixed rewrite for the same product on a category
save. This script resolves each product id to a SKU over REST, reads that
product's url_rewrite rows from a read-only export or admin-exposed rewrite
list (url_rewrite has no public REST search endpoint), flags the duplicate
pairs with a pure function, and only performs a guarded delete of the
redundant row when --apply is explicitly passed. Report only by default.

Guide: https://www.allanninal.dev/magento/disabled-rewrite-setting-still-duplicates/
"""
import os
import sys
import csv
import logging
import requests

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("disabled_rewrite_setting_still_duplicates")

MAGENTO_URL = os.environ["MAGENTO_URL"].rstrip("/")
TOKEN = os.environ["MAGENTO_ADMIN_TOKEN"]
HEADERS = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}
DRY_RUN = os.environ.get("DRY_RUN", "true").lower() == "true"
GENERATE_CATEGORY_PRODUCT_REWRITES = os.environ.get(
    "GENERATE_CATEGORY_PRODUCT_REWRITES", "false"
).lower() == "true"
PRODUCT_IDS = [
    int(p) for p in os.environ.get("PRODUCT_IDS", "").split(",") if p.strip()
]
URL_REWRITE_EXPORT_CSV = os.environ.get("URL_REWRITE_EXPORT_CSV", "url_rewrite_export.csv")


def api_get(path, params=None):
    r = requests.get(f"{MAGENTO_URL}/rest/V1{path}", headers=HEADERS, params=params or {}, timeout=30)
    r.raise_for_status()
    return r.json()


def api_delete(path):
    r = requests.delete(f"{MAGENTO_URL}/rest/V1{path}", headers=HEADERS, timeout=30)
    r.raise_for_status()
    return r.json()


def resolve_sku_by_entity_id(product_id):
    """GET /rest/V1/products filtered by entity_id, since url_rewrite itself
    has no direct REST search endpoint. Returns the product item or None."""
    params = {
        "searchCriteria[filterGroups][0][filters][0][field]": "entity_id",
        "searchCriteria[filterGroups][0][filters][0][value]": product_id,
        "searchCriteria[filterGroups][0][filters][0][conditionType]": "eq",
    }
    result = api_get("/products", params)
    items = result.get("items", [])
    return items[0] if items else None


def custom_attr(attrs, code, default=None):
    for a in attrs or []:
        if a.get("attribute_code") == code:
            return a.get("value")
    return default


def read_url_rewrite_rows_for_product(product_id, path=None):
    """Read this product's url_rewrite rows from a read-only export or
    admin-exposed rewrite list. url_rewrite has no public REST search
    endpoint, so this is produced by an Admin grid export or a read-only
    DB query, keyed on entity_type='product' and entity_id=product_id.
    CSV columns: url_rewrite_id, entity_type, entity_id, request_path,
    target_path, store_id, is_autogenerated."""
    path = path or URL_REWRITE_EXPORT_CSV
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["entity_type"] != "product" or int(row["entity_id"]) != product_id:
                continue
            rows.append({
                "url_rewrite_id": int(row["url_rewrite_id"]),
                "entity_type": row["entity_type"],
                "entity_id": int(row["entity_id"]),
                "request_path": row["request_path"],
                "target_path": row["target_path"],
                "store_id": int(row["store_id"]),
                "is_autogenerated": int(row.get("is_autogenerated", 0) or 0),
            })
    return rows


def find_duplicate_product_rewrites(rows, product_id, generate_category_rewrites_enabled):
    """Pure decision function.

    Filters rows to entity_type == 'product' and entity_id == product_id,
    groups by store_id, and within each group finds pairs sharing the same
    target_path (i.e. the same underlying product) where one request_path
    has more path segments than the other (category-prefixed). If
    generate_category_rewrites_enabled is False and more than one such row
    exists per store_id, returns pairs marking the shorter/non-category
    request_path as keep and the longer/category-containing one as remove,
    with reason 'duplicate-despite-disabled-setting'. Returns an empty list
    when only one row exists per store_id, or when the setting is enabled
    (duplicates may then be legitimate multi-category assignments).
    """
    if generate_category_rewrites_enabled:
        return []

    product_rows = [
        r for r in rows
        if r.get("entity_type") == "product" and r.get("entity_id") == product_id
    ]

    by_store = {}
    for row in product_rows:
        by_store.setdefault(row["store_id"], []).append(row)

    pairs = []
    for store_id, store_rows in by_store.items():
        by_target = {}
        for row in store_rows:
            by_target.setdefault(row["target_path"], []).append(row)
        for target_path, target_rows in by_target.items():
            if len(target_rows) <= 1:
                continue
            ordered = sorted(target_rows, key=lambda r: r["request_path"].count("/"))
            keep_row = ordered[0]
            for remove_row in ordered[1:]:
                if remove_row["request_path"].count("/") > keep_row["request_path"].count("/"):
                    pairs.append({
                        "keep": keep_row["url_rewrite_id"],
                        "remove": remove_row["url_rewrite_id"],
                        "reason": "duplicate-despite-disabled-setting",
                    })
    return pairs


def is_live_traffic_row(row, current_url_key):
    """Never remove the plain row matching the product's current url_key,
    since that is the row Magento's own default canonical preference and
    live traffic are currently using. Compares the whole request_path, not
    just its last segment, so a category-prefixed path such as
    mens/shirts/green-shirt.html is never mistaken for the plain
    green-shirt.html row just because they share a final segment."""
    if not current_url_key:
        return False
    return row["request_path"].rstrip("/") == f"{current_url_key}.html"


def run():
    apply_deletes = "--apply" in sys.argv
    total_pairs = 0

    for product_id in PRODUCT_IDS:
        product = resolve_sku_by_entity_id(product_id)
        if not product:
            log.info("Product id=%s not found, skipping", product_id)
            continue
        sku = product["sku"]
        current_url_key = custom_attr(product.get("custom_attributes"), "url_key", "")

        rows = read_url_rewrite_rows_for_product(product_id)
        pairs = find_duplicate_product_rewrites(rows, product_id, GENERATE_CATEGORY_PRODUCT_REWRITES)

        for pair in pairs:
            total_pairs += 1
            log.warning(
                "Product id=%s sku=%s: url_rewrite_id=%s is redundant next to keep=%s (%s)",
                product_id, sku, pair["remove"], pair["keep"], pair["reason"],
            )
            remove_row = next(r for r in rows if r["url_rewrite_id"] == pair["remove"])
            if is_live_traffic_row(remove_row, current_url_key):
                log.info("Skipping delete: row matches the product's current url_key, serving live traffic")
                continue
            if not apply_deletes or DRY_RUN:
                log.info(
                    "Recommend: apply the core patch for issue 38317/39070, or add an "
                    "after-plugin on CanonicalUrlRewriteGenerator::generate to drop this row. "
                    "Would delete url_rewrite_id=%s (pass --apply and DRY_RUN=false to delete)",
                    pair["remove"],
                )
                continue
            api_delete(f"/url-rewrites/{pair['remove']}")
            log.info("Deleted redundant url_rewrite_id=%s", pair["remove"])

    log.info("Done. %d duplicate pair(s) found across %d product(s).", total_pairs, len(PRODUCT_IDS))


if __name__ == "__main__":
    run()
