from disabled_rewrite_setting_still_duplicates import (
    find_duplicate_product_rewrites,
    is_live_traffic_row,
)


def row(**over):
    base = {
        "url_rewrite_id": 1,
        "entity_type": "product",
        "entity_id": 42,
        "request_path": "green-shirt.html",
        "target_path": "catalog/product/view/id/42",
        "store_id": 1,
        "is_autogenerated": 1,
    }
    base.update(over)
    return base


def test_no_pairs_when_setting_enabled():
    rows = [
        row(url_rewrite_id=1, request_path="green-shirt.html"),
        row(url_rewrite_id=2, request_path="mens/shirts/green-shirt.html"),
    ]
    assert find_duplicate_product_rewrites(rows, 42, True) == []


def test_no_pairs_when_only_one_row_per_store():
    rows = [row(url_rewrite_id=1, request_path="green-shirt.html")]
    assert find_duplicate_product_rewrites(rows, 42, False) == []


def test_flags_pair_when_setting_disabled_and_two_rows_share_target():
    rows = [
        row(url_rewrite_id=1, request_path="green-shirt.html"),
        row(url_rewrite_id=2, request_path="mens/shirts/green-shirt.html"),
    ]
    result = find_duplicate_product_rewrites(rows, 42, False)
    assert result == [
        {"keep": 1, "remove": 2, "reason": "duplicate-despite-disabled-setting"}
    ]


def test_ignores_rows_for_a_different_product():
    rows = [
        row(url_rewrite_id=1, entity_id=42, request_path="green-shirt.html"),
        row(url_rewrite_id=2, entity_id=99, request_path="blue-shirt.html"),
    ]
    assert find_duplicate_product_rewrites(rows, 42, False) == []


def test_ignores_rows_for_a_different_entity_type():
    rows = [
        row(url_rewrite_id=1, entity_type="product", request_path="green-shirt.html"),
        row(
            url_rewrite_id=2,
            entity_type="category",
            request_path="mens/shirts.html",
            target_path="catalog/category/view/id/7",
        ),
    ]
    assert find_duplicate_product_rewrites(rows, 42, False) == []


def test_same_target_different_store_is_not_paired():
    rows = [
        row(url_rewrite_id=1, request_path="green-shirt.html", store_id=1),
        row(url_rewrite_id=2, request_path="mens/shirts/green-shirt.html", store_id=2),
    ]
    assert find_duplicate_product_rewrites(rows, 42, False) == []


def test_different_target_path_is_not_paired():
    rows = [
        row(url_rewrite_id=1, request_path="green-shirt.html", target_path="catalog/product/view/id/42"),
        row(url_rewrite_id=2, request_path="mens/shirts/red-shirt.html", target_path="catalog/product/view/id/99"),
    ]
    assert find_duplicate_product_rewrites(rows, 42, False) == []


def test_duplicate_ids_pairs_are_returned_for_each_store_independently():
    rows = [
        row(url_rewrite_id=1, request_path="green-shirt.html", store_id=1),
        row(url_rewrite_id=2, request_path="mens/shirts/green-shirt.html", store_id=1),
        row(url_rewrite_id=3, request_path="green-shirt.html", store_id=2),
        row(url_rewrite_id=4, request_path="mens/shirts/green-shirt.html", store_id=2),
    ]
    result = find_duplicate_product_rewrites(rows, 42, False)
    assert {"keep": 1, "remove": 2, "reason": "duplicate-despite-disabled-setting"} in result
    assert {"keep": 3, "remove": 4, "reason": "duplicate-despite-disabled-setting"} in result
    assert len(result) == 2


def test_is_live_traffic_row_matches_current_url_key():
    r = row(request_path="green-shirt.html")
    assert is_live_traffic_row(r, "green-shirt") is True


def test_is_live_traffic_row_does_not_match_category_path():
    r = row(request_path="mens/shirts/green-shirt.html")
    assert is_live_traffic_row(r, "green-shirt") is False


def test_is_live_traffic_row_false_when_no_current_url_key():
    r = row(request_path="green-shirt.html")
    assert is_live_traffic_row(r, "") is False
