"""Detect duplicate Magento url_key collisions that block a product resave,
and repair the fixable ones, safely.

Magento 1 and many external carts or PIMs never enforced url_key uniqueness,
so a migrated catalog can carry two or more products whose url_key collides
once the store's URL suffix and category path are applied. Magento 2
enforces a unique constraint on url_rewrite(request_path, store_id), so
resaving one of the colliding products throws AlreadyExistsException.

This script fetches every product over REST, groups them by their expected
request_path, keeps the row Magento already treats as authoritative (a
manual redirect over an autogenerated one, else the lowest entity_id), and
proposes a new url_key of sku-original_url_key for every other colliding
product. It only calls the repair PUT when DRY_RUN=false, because renaming
a live url_key changes a public-facing SEO URL. Report only by default.
"""
import os
import re
import logging
import requests

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("duplicate_url_key")

MAGENTO_URL = os.environ["MAGENTO_URL"].rstrip("/")
TOKEN = os.environ["MAGENTO_ADMIN_TOKEN"]
HEADERS = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}
URL_SUFFIX = os.environ.get("URL_SUFFIX", ".html")
DRY_RUN = os.environ.get("DRY_RUN", "true").lower() == "true"


def api_get(path, params=None):
    r = requests.get(f"{MAGENTO_URL}/rest/V1{path}", headers=HEADERS, params=params or {}, timeout=30)
    r.raise_for_status()
    return r.json()


def api_put(path, payload):
    r = requests.put(f"{MAGENTO_URL}/rest/V1{path}", headers=HEADERS, json=payload, timeout=30)
    r.raise_for_status()
    return r.json()


def custom_attr(attrs, code, default=None):
    for a in attrs or []:
        if a.get("attribute_code") == code:
            return a.get("value")
    return default


def fetch_products():
    products, page = [], 1
    while True:
        params = {"searchCriteria[pageSize]": 100, "searchCriteria[currentPage]": page}
        result = api_get("/products", params)
        items = result.get("items", [])
        for item in items:
            products.append({
                "sku": item["sku"],
                "entityId": item["id"],
                "urlKey": custom_attr(item.get("custom_attributes"), "url_key", item["sku"]),
                "updatedAt": item.get("updated_at", ""),
            })
        if len(items) < 100:
            return products
        page += 1


def build_request_path_index(products, url_suffix):
    """Fallback index built from products alone, grouping by the expected
    request_path (url_key + suffix). A real migration should instead read
    url_rewrite directly for is_autogenerated accuracy; this covers the
    common case where two products share or normalize to one request_path."""
    index = {}
    for p in products:
        request_path = f"{p['urlKey']}{url_suffix}"
        index.setdefault(request_path, []).append({
            "entityId": p["entityId"],
            "requestPath": request_path,
            "storeId": 1,
            "isAutogenerated": True,
        })
    return index


def slugify(value):
    value = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return re.sub(r"-+", "-", value)


def pick_keeper(rows):
    manual = [r for r in rows if not r.get("isAutogenerated", True)]
    if manual:
        return min(manual, key=lambda r: r["entityId"])
    return min(rows, key=lambda r: r["entityId"])


def resolve_url_key_collisions(products, request_path_index):
    """Pure decision function. Groups url_rewrite rows by (request_path,
    store_id) via request_path_index, and for any group spanning more than
    one entity_id, picks a keeper (manual redirect over autogenerated, else
    lowest entityId), and derives a deterministic new url_key of
    sku-original_url_key (lowercased, slugified) for every other product in
    the group. No HTTP or DB calls; fully unit-testable with fixtures."""
    decisions = []
    for request_path, rows in request_path_index.items():
        entity_ids = {r["entityId"] for r in rows}
        if len(entity_ids) <= 1:
            continue
        keeper_row = pick_keeper(rows)
        for row in rows:
            product = next((p for p in products if p["entityId"] == row["entityId"]), None)
            if product is None:
                continue
            if row["entityId"] == keeper_row["entityId"]:
                decisions.append({
                    "sku": product["sku"], "oldUrlKey": product["urlKey"],
                    "newUrlKey": product["urlKey"], "requestPath": request_path, "action": "keep",
                })
            else:
                new_key = slugify(f"{product['sku']}-{product['urlKey']}")
                decisions.append({
                    "sku": product["sku"], "oldUrlKey": product["urlKey"],
                    "newUrlKey": new_key, "requestPath": request_path, "action": "rename",
                })
    return decisions


def rename_url_key(sku, new_url_key):
    payload = {"product": {"sku": sku, "custom_attributes": [
        {"attribute_code": "url_key", "value": new_url_key}
    ]}}
    return api_put(f"/products/{sku}", payload)


def run():
    products = fetch_products()
    request_path_index = build_request_path_index(products, URL_SUFFIX)
    decisions = resolve_url_key_collisions(products, request_path_index)

    renamed = 0
    for decision in decisions:
        if decision["action"] != "rename":
            continue
        log.warning(
            "Collision on %s: sku=%s %s -> %s",
            decision["requestPath"], decision["sku"], decision["oldUrlKey"], decision["newUrlKey"],
        )
        if not DRY_RUN:
            rename_url_key(decision["sku"], decision["newUrlKey"])
        renamed += 1

    log.info("Done. %d colliding product(s) %s.", renamed, "to rename" if DRY_RUN else "renamed")


if __name__ == "__main__":
    run()
