from duplicate_url_key import resolve_url_key_collisions


def product(**over):
    base = {"sku": "SKU-1", "entityId": 1, "urlKey": "blue-widget", "updatedAt": "2026-01-01T00:00:00Z"}
    base.update(over)
    return base


def row(**over):
    base = {"entityId": 1, "requestPath": "blue-widget.html", "storeId": 1, "isAutogenerated": True}
    base.update(over)
    return base


def test_no_decisions_when_request_path_is_unique():
    products = [product(sku="SKU-1", entityId=1)]
    index = {"blue-widget.html": [row(entityId=1)]}
    assert resolve_url_key_collisions(products, index) == []


def test_lowest_entity_id_is_kept_when_both_autogenerated():
    products = [product(sku="SKU-1", entityId=1), product(sku="SKU-2", entityId=2, urlKey="blue-widget")]
    index = {"blue-widget.html": [row(entityId=1), row(entityId=2)]}
    decisions = resolve_url_key_collisions(products, index)
    kept = next(d for d in decisions if d["action"] == "keep")
    renamed = next(d for d in decisions if d["action"] == "rename")
    assert kept["sku"] == "SKU-1"
    assert renamed["sku"] == "SKU-2"
    assert renamed["newUrlKey"] == "sku-2-blue-widget"


def test_manual_redirect_is_kept_over_autogenerated():
    products = [product(sku="SKU-1", entityId=1), product(sku="SKU-2", entityId=2, urlKey="blue-widget")]
    index = {"blue-widget.html": [row(entityId=1, isAutogenerated=True), row(entityId=2, isAutogenerated=False)]}
    decisions = resolve_url_key_collisions(products, index)
    kept = next(d for d in decisions if d["action"] == "keep")
    assert kept["sku"] == "SKU-2"


def test_new_url_key_is_slugified():
    products = [product(sku="SKU-1", entityId=1), product(sku="SKU 2!", entityId=2, urlKey="Blue Widget")]
    index = {"blue-widget.html": [row(entityId=1), row(entityId=2)]}
    decisions = resolve_url_key_collisions(products, index)
    renamed = next(d for d in decisions if d["action"] == "rename")
    assert renamed["newUrlKey"] == "sku-2-blue-widget"


def test_three_way_collision_keeps_only_one():
    products = [product(sku="A", entityId=3), product(sku="B", entityId=1), product(sku="C", entityId=2)]
    index = {"blue-widget.html": [row(entityId=3), row(entityId=1), row(entityId=2)]}
    decisions = resolve_url_key_collisions(products, index)
    kept = [d for d in decisions if d["action"] == "keep"]
    renamed = [d for d in decisions if d["action"] == "rename"]
    assert len(kept) == 1
    assert kept[0]["sku"] == "B"
    assert len(renamed) == 2


def test_missing_product_for_a_row_is_skipped():
    products = [product(sku="SKU-1", entityId=1)]
    index = {"blue-widget.html": [row(entityId=1), row(entityId=99)]}
    decisions = resolve_url_key_collisions(products, index)
    assert all(d["sku"] != "" for d in decisions)
    assert len(decisions) == 1


def test_different_store_ids_do_not_collide_when_grouped_separately():
    products = [product(sku="SKU-1", entityId=1), product(sku="SKU-2", entityId=2, urlKey="blue-widget")]
    index = {
        "blue-widget.html-store1": [row(entityId=1, storeId=1)],
        "blue-widget.html-store2": [row(entityId=2, storeId=2)],
    }
    decisions = resolve_url_key_collisions(products, index)
    assert decisions == []
